version: "3.4"

services:
  db:
    hostname: db
    build:
      context: ./docker/db
    volumes:
      - ./:/src
    working_dir: /src/
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: apollo
      POSTGRES_PASSWORD: apollo
      POSTGRES_DB: apollo
