// Code generated by sqlc. DO NOT EDIT.

package internal

import (
	"database/sql"
	"time"

	"github.com/segmentio/ksuid"
)

// Approved connections that exist between users
type ApolloConnection struct {
	ID          int64
	RequesterID ksuid.KSUID
	ApproverID  ksuid.KSUID
	CreatedAt   time.Time
}

// Requested connections between users
type ApolloRequest struct {
	ID          int64
	RequesterID ksuid.KSUID
	ApproverID  ksuid.KSUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Users inside the safety network
type ApolloUser struct {
	Ksuid        ksuid.KSUID
	FirstName    string
	LastName     string
	Phone        int64
	PhoneCountry int32
	Dob          time.Time
	OrganDonor   sql.NullBool
	MedicalInfo  sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
